import type { CanonFragment } from './types';

/** Canon fragments — domain: conflict. */
export const CONFLICT_FRAGMENTS: CanonFragment[] = [
  // ═══ JUNG — 16 types × conflict ═══
  { id: 'jung:INTJ:conflict', system: 'jung', key: 'INTJ', domain: 'conflict', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'You approach conflict as a problem to solve, not an emotion to feel. This makes you effective in negotiations and infuriating in personal arguments. Your partner hears logical deconstruction where they wanted acknowledgment. The practice: before you analyse the conflict, say one sentence that validates the other person\'s feeling. "I understand this matters to you" costs nothing and changes the entire trajectory of the conversation. Solve second; acknowledge first.' },
  { id: 'jung:INTP:conflict', system: 'jung', key: 'INTP', domain: 'conflict', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'You avoid conflict until you can no longer avoid it, and then you dissect it with surgical precision that the other person experiences as cold. You do not intend cruelty — you intend clarity. The gap between those two is the conflict itself. The practice: engage earlier. A short conversation at mild discomfort prevents the long one at high intensity. Say "something is bothering me, and I have not fully articulated it yet" — this invites dialogue before you have weaponised the analysis.' },
  { id: 'jung:ENTJ:conflict', system: 'jung', key: 'ENTJ', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'You engage conflict directly and expect resolution quickly. For you, the disagreement is a problem; identify it, debate it, decide, move on. The person across from you may need processing time you are unwilling to grant. The practice: state your position once, clearly, then ask for a response by a specific time. "I have said what I think. Can we continue this tomorrow?" gives the other person room to organise their thoughts without your pace dictating the outcome.' },
  { id: 'jung:ENTP:conflict', system: 'jung', key: 'ENTP', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'You enjoy conflict. Not the pain — the energy. Debate sharpens your thinking, and you often escalate just to see where the argument goes. The person across from you may not share this enthusiasm. The practice: before you counter-argue, ask yourself whether you are debating the issue or performing. If the goal is resolution, listen. If the goal is intellectual stimulation, admit it and find a willing sparring partner instead of an unwilling opponent.' },
  { id: 'jung:INFJ:conflict', system: 'jung', key: 'INFJ', domain: 'conflict', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'You absorb conflict like a sponge and process it internally for days. By the time you speak, you have composed a complete narrative of the disagreement — its cause, its subtext, and its resolution — and you deliver it as a monologue the other person was not expecting. The practice: break the monologue into smaller conversations. Share the concern before the thesis is complete. "I have been thinking about last Tuesday" opens a dialogue. A fully formed analysis opens a lecture.' },
  { id: 'jung:INFP:conflict', system: 'jung', key: 'INFP', domain: 'conflict', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'You avoid conflict until a value is violated, and then you fight with a quiet intensity that surprises everyone, including yourself. Your anger is rare but total — it comes from a place so deep that it does not know how to be moderate. The practice: voice the small irritations before they become value violations. A boundary spoken at low heat prevents the eruption that arrives at high heat. Your anger is righteous; your timing is the variable you can control.' },
  { id: 'jung:ENFJ:conflict', system: 'jung', key: 'ENFJ', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'You try to resolve conflict before it fully arrives, smoothing disagreements into compromises that leave everyone partially satisfied and no one fully heard. Your instinct is to harmonise, but some conflicts need to be felt before they can be resolved. The practice: let the disagreement exist for one conversation without trying to fix it. Ask "what do you need me to understand?" instead of "how can we solve this?" Understanding precedes resolution; skip it and the resolution will not hold.' },
  { id: 'jung:ENFP:conflict', system: 'jung', key: 'ENFP', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'You experience conflict as a threat to connection, and your first instinct is to restore warmth. You apologise quickly, sometimes before understanding what you are apologising for. The cost: the underlying issue remains, and the cycle repeats. The practice: hold the discomfort for one beat longer before you reconcile. Ask "what just happened?" and listen to the full answer. An apology that follows understanding prevents recurrence; an apology that replaces it does not.' },
  { id: 'jung:ISTJ:conflict', system: 'jung', key: 'ISTJ', domain: 'conflict', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'You approach conflict with facts and precedent. "We agreed to X, you did Y" is your opening move, and it is effective in contractual disputes and devastating in personal ones. Your partner does not want to be cross-examined. The practice: separate the factual grievance from the emotional one. Lead with "I felt frustrated" before you present the evidence. The feeling is the point; the facts are the supporting material, not the headline.' },
  { id: 'jung:ISFJ:conflict', system: 'jung', key: 'ISFJ', domain: 'conflict', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'You absorb conflict without expressing it, storing grievances in a ledger that the other person does not know exists. When the ledger finally tips, the eruption includes items from months or years ago. The practice: express one discomfort per week, when it is small. "That bothered me" spoken today prevents "you always do this" spoken in six months. Your kindness is genuine; it does not require you to be silent about hurt.' },
  { id: 'jung:ESTJ:conflict', system: 'jung', key: 'ESTJ', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'You confront directly, with volume and certainty. Your conflict style is efficient: identify the problem, state the expectation, enforce the standard. In professional settings this works; in personal ones it bulldozes. The practice: lower your volume by one notch and replace one statement with one question. "What happened?" before "Here is what should have happened" changes the other person from defendant to participant.' },
  { id: 'jung:ESFJ:conflict', system: 'jung', key: 'ESFJ', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Conflict feels like a relationship failure to you, and you will go to extraordinary lengths to prevent it. When it arrives anyway, you are hurt more by the rupture than by the issue itself. The practice: reframe conflict as maintenance, not failure. Every relationship has disagreements; the ones that survive are not the ones that avoid them but the ones that process them honestly. Your willingness to engage honestly, not just pleasantly, is what makes the relationship real.' },
  { id: 'jung:ISTP:conflict', system: 'jung', key: 'ISTP', domain: 'conflict', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'You disengage from emotional conflict — not because you do not care, but because the emotional register feels foreign and the most logical response seems to be leaving until it passes. Your partner reads this as abandonment. The practice: say "I need thirty minutes to think about this" instead of walking away silently. The difference is one sentence, and it changes the meaning of your departure from rejection to processing. Come back when you said you would.' },
  { id: 'jung:ISFP:conflict', system: 'jung', key: 'ISFP', domain: 'conflict', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'You withdraw from conflict into your inner world, where you process the hurt privately. From the outside, this looks like sulking or passive aggression; from the inside, it is self-protection. The practice: narrate the withdrawal. "I am hurt and need space to process" tells the other person what is happening. You do not need to fight in the moment — you need to communicate that you have not left, you have only stepped back to feel.' },
  { id: 'jung:ESTP:conflict', system: 'jung', key: 'ESTP', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'You confront immediately and impatiently. You say the hard thing, deal with the fallout, and move on. This speed is effective in crises and destructive in intimate disagreements where the other person needs time. The practice: after your opening statement, stop and count to five. Let the other person respond before you escalate. Your instinct is to resolve through action; some conflicts require the inaction of listening, which is a different kind of courage.' },
  { id: 'jung:ESFP:conflict', system: 'jung', key: 'ESFP', domain: 'conflict', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'You want the conflict to end so the good times can resume. Your instinct is to defuse with humour, charm, or distraction. When that fails, you feel genuinely lost. The practice: stay in the discomfort for three exchanges past where you normally redirect. "Tell me more" is a phrase that extends the conversation into the territory where real resolution lives. Your social genius is best applied after the hard part, not instead of it.' },

  // ═══ ENNEAGRAM — 9 cores × conflict ═══
  { id: 'ennea:1:conflict', system: 'ennea', key: '1', domain: 'conflict', traitIds: ['enneagram:reformer-standards', 'enneagram:reformer-critic'], text: 'You argue from principle, which makes you feel righteous and makes the other person feel condemned. You are not attacking — you are upholding a standard. But the effect is the same. The practice: before stating the principle, state the relationship. "I value you, and this matters to me because..." connects the standard to the person instead of using the standard against them. Your principles do not need to soften; their delivery does.' },
  { id: 'ennea:2:conflict', system: 'ennea', key: '2', domain: 'conflict', traitIds: ['enneagram:helper-attunement', 'enneagram:helper-giving'], text: 'You avoid direct conflict and express grievances through withdrawal of warmth. The person who was getting your full attention suddenly gets your polite distance, and they have to decode what happened. The practice: say the thing directly. "I felt unappreciated when you did not acknowledge what I made for dinner" is clearer, kinder, and faster than two days of cool politeness. Direct conflict is less painful than the passive kind you default to.' },
  { id: 'ennea:3:conflict', system: 'ennea', key: '3', domain: 'conflict', traitIds: ['enneagram:achiever-drive', 'enneagram:achiever-adapt'], text: 'You reframe conflict as a challenge to win. You pivot, adapt your argument, and outmanoeuvre rather than listen. This makes you effective in boardrooms and exhausting in bedrooms. The practice: in your next personal disagreement, resist the urge to counter-argue. Instead, repeat back what the other person said until they confirm you understood it. Winning the argument loses the relationship; understanding the argument is how you win it back.' },
  { id: 'ennea:4:conflict', system: 'ennea', key: '4', domain: 'conflict', traitIds: ['enneagram:individualist-depth', 'enneagram:individualist-longing'], text: 'You feel conflict at a volume that others do not match, and the intensity of your emotional response can overwhelm the other person. What felt like a disagreement to them felt like a crisis to you. The practice: name the scale of what you are feeling. "This feels enormous to me — I know it might not to you, and I am not asking you to match it." This one sentence bridges the gap between your emotional world and theirs.' },
  { id: 'ennea:5:conflict', system: 'ennea', key: '5', domain: 'conflict', traitIds: ['enneagram:investigator-detach', 'enneagram:investigator-conserve'], text: 'You retreat from conflict to analyse it, often returning hours or days later with a precise, detached reading that the other person has long since moved past. Your timing is always off because your process is internal. The practice: engage in real-time, even imperfectly. Say "I notice a disagreement. I need time to think, but I want you to know I am not dismissing it." This keeps the channel open while honouring your need to process.' },
  { id: 'ennea:6:conflict', system: 'ennea', key: '6', domain: 'conflict', traitIds: ['enneagram:loyalist-vigilance', 'enneagram:loyalist-questioning'], text: 'You anticipate conflict before it arrives and prepare for it so thoroughly that you sometimes create it. Your worst-case scenarios generate defensive behaviour that the other person has to respond to. The practice: before raising a concern, ask "Is this happening, or am I preparing for it?" If the answer is preparing, hold it. Address what is real. Your vigilance is best applied to actual threats, not rehearsed ones.' },
  { id: 'ennea:7:conflict', system: 'ennea', key: '7', domain: 'conflict', traitIds: ['enneagram:enthusiast-optimism', 'enneagram:enthusiast-avoidance'], text: 'You reframe conflict into positivity so quickly that the other person feels gaslit. Their pain is real, and your "let us look at the bright side" dismisses it. The practice: before you reframe, reflect. "That sounds painful" spoken first, with a full pause after it, changes everything. You do not need to stay in the pain forever — you need to stay long enough for the other person to know you saw it.' },
  { id: 'ennea:8:conflict', system: 'ennea', key: '8', domain: 'conflict', traitIds: ['enneagram:challenger-directness', 'enneagram:challenger-control'], text: 'Conflict does not frighten you; its absence does. You escalate to find out who is real, and you respect whoever stays standing. The cost is invisible to you in the moment: most people experience your clarity as force, and force makes them comply instead of engage — which leaves you surrounded by agreement you cannot trust, the exact thing you were testing for. Before you raise the stakes, name them: "I am pushing because this matters, not against you." Watch for the flat voice of someone who has stopped fighting; that is not peace, that is retreat.' },
  { id: 'ennea:9:conflict', system: 'ennea', key: '9', domain: 'conflict', traitIds: ['enneagram:peacemaker-harmony', 'enneagram:peacemaker-numbing'], text: 'You avoid conflict by merging with the other person\'s position, and the cost is invisible for a long time. Then, unpredictably, you erupt — or simply leave, having accumulated so much unexpressed frustration that departure feels like the only honest act. The practice: express one preference per day. Not a complaint — a preference. "I would rather eat at home tonight." Conflict prevention for the Nine is the daily practice of having a visible opinion before the opinions stack into a crisis.' },

  // ═══ HUMAN DESIGN — 5 types × conflict ═══
  { id: 'hd:Generator:conflict', system: 'hd', key: 'Generator', domain: 'conflict', traitIds: ['hd:sacral-energy'], text: 'Your sacral response tells you when something is wrong before your mind catches up. A frustrated grunt, a tightening in the belly, a sudden drop in energy — these are your conflict signals. The practice: trust the body. When the sacral contracts, something needs to be addressed. Do not override the signal with rationalisations. Say "something about this is not working for me" and then investigate. Your body is a more honest conflict detector than your mind.' },
  { id: 'hd:Manifesting Generator:conflict', system: 'hd', key: 'Manifesting Generator', domain: 'conflict', traitIds: ['hd:multi-passionate'], text: 'You process conflict at high speed and may resolve it internally before the other person has finished their opening statement. This makes you seem dismissive. The practice: match the other person\'s pace, not your own. Repeat what they said before responding. "What I hear is..." slows you down enough for the conversation to be mutual. Your speed is an asset in execution and a liability in conflict; deliberately downshift.' },
  { id: 'hd:Projector:conflict', system: 'hd', key: 'Projector', domain: 'conflict', traitIds: ['hd:seeing-gift'], text: 'You see the root cause of the conflict with painful clarity. The danger: you name it uninvited, and the other person feels exposed rather than helped. The practice: wait until you are asked for your perspective, or create the conditions for asking. "I think I see what is happening here — would it be helpful to hear it?" gives the other person a choice. Your insight in conflict is a precision instrument; wielded without consent, it cuts instead of heals.' },
  { id: 'hd:Manifestor:conflict', system: 'hd', key: 'Manifestor', domain: 'conflict', traitIds: ['hd:initiating-force'], text: 'You initiate conflict with the same force you bring to everything else: directly, decisively, and with the expectation that it will be resolved by your terms. The cost: the other person feels rolled over. The practice: after you have stated your position, say "your turn" and then be silent. Conflict resolution for the Manifestor requires the unnatural act of waiting. Your design is to initiate, not to dominate; the distinction matters.' },
  { id: 'hd:Reflector:conflict', system: 'hd', key: 'Reflector', domain: 'conflict', traitIds: ['hd:mirror-quality'], text: 'You absorb the emotional intensity of conflict from the environment, which means you may be fighting someone else\'s fight without realising it. The practice: before you engage, ask "Is this mine?" If the anger, frustration, or hurt fades when you leave the room, it was not yours. Address only the conflicts that remain after twenty-four hours of solitude. Those are the real ones. Everything else is the environment speaking through you.' },

  // ═══ MILLMAN — finals 1–12 × conflict ═══
  { id: 'millman:1:conflict', system: 'millman', key: '1', domain: 'conflict', traitIds: ['millman:creative-independence'], text: 'Your conflict style is to withdraw and create alone rather than engage in the argument. This protects your creative energy and abandons the relationship. The practice: re-enter one avoided conflict this week with a single sentence: "I left because I did not know how to say this." That opening is honest, and honesty is the bridge between your independence and the connection the other person needs.' },
  { id: 'millman:2:conflict', system: 'millman', key: '2', domain: 'conflict', traitIds: ['millman:cooperative-sensitivity'], text: 'You over-accommodate in conflict, giving ground until you have no position left. Then the resentment arrives, and the conflict that should have been small becomes existential. The practice: state your position early and hold it. "I disagree" spoken calmly in the first minute is worth more than a capitulation followed by weeks of silent fury.' },
  { id: 'millman:3:conflict', system: 'millman', key: '3', domain: 'conflict', traitIds: ['millman:expressive-gift'], text: 'Your words are your weapon and your bridge. In conflict, you can wound with precision or heal with clarity — the same gift produces both. The practice: before you speak in conflict, choose which function you want the words to serve. If the answer is "I want them to feel what I felt," pause. Retaliation expressed eloquently is still retaliation. Redirect the gift toward understanding.' },
  { id: 'millman:4:conflict', system: 'millman', key: '4', domain: 'conflict', traitIds: ['millman:builder-persistence'], text: 'You bring patience and process to conflict, which means you outlast the other person but do not always outresolve them. Your persistence can feel like stubbornness. The practice: set a time limit for the conversation. "Let us talk about this for twenty minutes and revisit tomorrow." Your process-oriented nature benefits from structure even in emotional territory.' },
  { id: 'millman:5:conflict', system: 'millman', key: '5', domain: 'conflict', traitIds: ['millman:freedom-discipline'], text: 'You fight for freedom — space, autonomy, the right to choose. When you feel constrained, your conflict energy rises sharply. The practice: name the constraint before you fight it. "I feel boxed in by this arrangement" is more productive than the escape attempt that follows. Your need for freedom is legitimate; the way you claim it determines whether the relationship survives the claiming.' },
  { id: 'millman:6:conflict', system: 'millman', key: '6', domain: 'conflict', traitIds: ['millman:visionary-standards'], text: 'You argue from the ideal, which makes you right in principle and wrong in practice. The other person does not live in your vision — they live in reality. The practice: start from where the other person actually is, not from where you think they should be. Conflict resolution on the 6 path begins with acceptance of the present, not assertion of the future.' },
  { id: 'millman:7:conflict', system: 'millman', key: '7', domain: 'conflict', traitIds: ['millman:inner-trust'], text: 'You sense conflict before it surfaces and may address issues the other person has not yet recognised. This feels prescient to you and presumptuous to them. The practice: frame your intuitive read as a question. "I sense something is off — am I reading this correctly?" opens dialogue. "I know what is wrong" closes it.' },
  { id: 'millman:8:conflict', system: 'millman', key: '8', domain: 'conflict', traitIds: ['millman:abundant-leadership'], text: 'You bring executive force to conflict: decisive, commanding, and oriented toward resolution on your terms. That force settles rooms quickly — and it can settle them into silence rather than agreement, which returns later as resistance. The practice: after you have stated your position, explicitly invite the other person\'s. "What would a fair resolution look like from your side?" demonstrates that your power includes the capacity to share it.' },
  { id: 'millman:9:conflict', system: 'millman', key: '9', domain: 'conflict', traitIds: ['millman:exemplar-integrity'], text: 'You hold yourself to a high standard in conflict and expect the same from others. When someone fights dirty, you feel not just hurt but morally offended. The practice: state your standard once — "I do not do personal attacks, and I ask the same" — and then model it. Your integrity in conflict is both your protection and your most powerful influence on the other person\'s behaviour.' },
  { id: 'millman:10:conflict', system: 'millman', key: '10', domain: 'conflict', traitIds: ['millman:creative-independence'], text: 'Your double-digit path gives you an ability to see conflict from a broader perspective than either party. The practice: use this gift to name the shared interest beneath the disagreement. "We both want X — we disagree about how to get there" reframes the conflict from opposition to collaboration on a shared problem.' },
  { id: 'millman:11:conflict', system: 'millman', key: '11', domain: 'conflict', traitIds: ['millman:creative-independence'], text: 'The doubled creative energy makes you sensitive in conflict — both to what is said and to what is implied. You read subtext that may not exist, and your response to the imagined slight can be stronger than the other person\'s actual offence. The practice: check your reading. "Did you mean X when you said Y?" separates your interpretation from their intention. The 11 in conflict needs to verify before it reacts.' },
  { id: 'millman:12:conflict', system: 'millman', key: '12', domain: 'conflict', traitIds: ['millman:creative-independence', 'millman:cooperative-sensitivity'], text: 'You hold both the creative individualist and the cooperative diplomat, which gives you the rare ability to advocate strongly and then genuinely listen. The practice: use both in sequence. State your truth, then ask for theirs. The 12 path in conflict is fulfilled not by winning or capitulating but by the honest exchange between two fully present people.' },
];
