import type { CanonFragment } from './types';

/** Canon fragments — domain: happiness. */
export const HAPPINESS_FRAGMENTS: CanonFragment[] = [
  // ═══ JUNG — 16 types × happiness ═══
  { id: 'jung:INTJ:happiness', system: 'jung', key: 'INTJ', domain: 'happiness', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Happiness for you is a well-solved problem and the quiet knowledge that no one else could have solved it that way. You do not need celebration; you need the internal confirmation that the architecture was right. Crowds, small talk, and forced fun deplete you. The practice: schedule one afternoon per week with no obligation and a hard problem. Protect it the way others protect their social time. Your happiness is not antisocial — it is structurally different, and it needs structural protection.' },
  { id: 'jung:INTP:happiness', system: 'jung', key: 'INTP', domain: 'happiness', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Happiness arrives in the moment when a complex idea suddenly resolves into clarity. The dopamine of understanding is your primary pleasure, and it requires solitude, time, and the absence of social obligation. Interruption is not a minor inconvenience — it is the destruction of a cognitive state that may take hours to rebuild. The practice: design your environment for flow. Noise-cancelling headphones, closed doors, and a calendar with visible blocks labelled "thinking." Your happiness depends on conditions you must actively create.' },
  { id: 'jung:ENTJ:happiness', system: 'jung', key: 'ENTJ', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Happiness for you is winning — not in a petty sense but in the strategic sense of marshalling resources toward an objective and watching the plan succeed. You are happiest in motion, with a clear target and a capable team. Stagnation is your depression. The practice: maintain a personal objective that is independent of your job. A fitness goal, a skill acquisition, a building project. When the professional sphere stalls, this parallel track keeps the strategic engine running and preserves your equilibrium.' },
  { id: 'jung:ENTP:happiness', system: 'jung', key: 'ENTP', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Happiness is a conversation where someone challenges your idea and neither of you backs down. You are happiest at the intersection of novelty and debate, where ideas collide and something unexpected emerges. Routine dulls you, agreement bores you, and certainty feels like death. The practice: seek out one person who thinks differently from you and schedule regular exchanges. Your happiness requires intellectual friction. Without it, your mind turns its restless energy inward, and that is not where it belongs.' },
  { id: 'jung:INFJ:happiness', system: 'jung', key: 'INFJ', domain: 'happiness', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Happiness for you is a deep, quiet connection with one person who understands you without explanation. You do not need many such people — one or two is sufficient, and the quality of that bond is worth more than any social calendar. Surface-level socializing drains you; meaningful conversation restores you. The practice: invest in the relationship that already understands you. A long letter, an honest conversation, a shared silence. Your happiness is relational but narrow, and honouring its narrowness is not a flaw.' },
  { id: 'jung:INFP:happiness', system: 'jung', key: 'INFP', domain: 'happiness', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Happiness is the feeling that you are living in alignment with your values and that your inner world is honoured by the way you spend your days. A beautiful book, a piece of music that moves you, a forest walk, or a conversation where someone truly listens — these are not minor pleasures, they are your primary ones. The practice: curate your daily environment for beauty and meaning. Remove one thing that clashes with your sensibility; add one that feeds it. Your happiness responds to aesthetic care as directly as a plant responds to light.' },
  { id: 'jung:ENFJ:happiness', system: 'jung', key: 'ENFJ', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Happiness for you is watching someone you mentored reach a moment of breakthrough. Your joy is relational and developmental — you are happiest when your influence helped someone grow. The risk: you make others\' happiness a prerequisite for your own and never arrive. The practice: celebrate one thing that belongs only to you this week. A meal you enjoyed, a skill you developed, a moment of rest. Your happiness must include chapters where you are the protagonist, not only the supporting cast.' },
  { id: 'jung:ENFP:happiness', system: 'jung', key: 'ENFP', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Happiness is the spark of a new possibility — a plan, a friendship, an idea that opens a door you did not know existed. You are happiest when the future feels wide open and the present is full of people you enjoy. The shadow: the spark fades, and the thing you were excited about yesterday feels ordinary today. The practice: distinguish between the happiness of discovery and the happiness of completion. You have abundant access to the first; the second requires staying with something past the novelty. Both are real.' },
  { id: 'jung:ISTJ:happiness', system: 'jung', key: 'ISTJ', domain: 'happiness', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Happiness is the satisfaction of a well-ordered life. A completed task, a balanced account, a promise kept, a tradition upheld. You do not need excitement — you need reliability, and the pleasure of knowing that what you built still stands. The risk: you optimize so thoroughly for stability that surprise becomes intolerable. The practice: introduce one small unpredictability per month. A new restaurant, a spontaneous drive, an unscheduled evening. Your happiness broadens when it includes the occasional departure from the plan.' },
  { id: 'jung:ISFJ:happiness', system: 'jung', key: 'ISFJ', domain: 'happiness', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Happiness for you lives in the details of care: a table set properly, a gift chosen thoughtfully, a friend remembered on a hard day. You find joy in the invisible labour of making life better for the people you love. The risk: you give without receiving and call the imbalance normal. The practice: accept one act of care from someone else this week without deflecting, diminishing, or immediately reciprocating. Your happiness includes being tended, not only tending.' },
  { id: 'jung:ESTJ:happiness', system: 'jung', key: 'ESTJ', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Happiness is the evidence that your efforts produced results. A successful event, a completed project, a team that performed well under your coordination. You take genuine pleasure in accomplishment and in the social recognition that accompanies it. The risk: you postpone happiness until the next achievement and never inhabit the current one. The practice: after each completion, pause for one full day before starting the next objective. Let the satisfaction register in your body, not just your calendar.' },
  { id: 'jung:ESFJ:happiness', system: 'jung', key: 'ESFJ', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Happiness is a room full of people you love, well fed, laughing, and connected. You are the host, the organizer, the one who made it happen. Social harmony is not a nice-to-have for you — it is a primary source of joy. The risk: you measure your happiness by others\' moods and give the weather of the room more power than your own inner state. The practice: check in with yourself before checking on others. "Am I happy?" is a question you are allowed to ask first.' },
  { id: 'jung:ISTP:happiness', system: 'jung', key: 'ISTP', domain: 'happiness', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Happiness is a tool in hand, a problem in front of you, and no one watching. You are happiest when you are doing — fixing, building, debugging, driving, operating. The pleasure is kinesthetic: you feel competence through your hands and your reflexes. Talking about feelings does not make you happier; demonstrating skill does. The practice: protect time for hands-on work. If your job has become entirely abstract, find a physical craft. Your happiness has a tactile dimension that screen work alone cannot supply.' },
  { id: 'jung:ISFP:happiness', system: 'jung', key: 'ISFP', domain: 'happiness', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Happiness lives in sensory beauty and quiet presence. A garden, a piece of music, a well-cooked meal, an afternoon with an animal or a close friend — these are not small pleasures for you, they are the centre of your emotional life. The world tells you to aim higher; your design says "aim deeper." The practice: honour the small. One intentional sensory experience per day — a particular tea, a specific light, a texture you love. Your happiness is cumulative and grounded in attention to the present moment.' },
  { id: 'jung:ESTP:happiness', system: 'jung', key: 'ESTP', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Happiness is the rush of action and the pleasure of a well-played hand. You are happiest when the stakes are real, the feedback is immediate, and you are performing. Sport, negotiation, travel, competition — anything where your reflexes and nerve translate directly into outcome. The risk: you chase the peak and cannot tolerate the valley. The practice: build a recovery ritual. After every intense experience, schedule something restorative. Your happiness needs downbeats as much as it needs crescendos.' },
  { id: 'jung:ESFP:happiness', system: 'jung', key: 'ESFP', domain: 'happiness', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Happiness is a shared experience: the concert, the dinner, the spontaneous road trip, the laughter that comes from being present together. You are happiest when the moment is vivid and the people around you are enjoying it too. Solitude in small doses restores you; in large ones it becomes loneliness. The practice: plan one experience per week that exists purely for joy, not for utility. Your happiness is not a reward for productivity — it is a need as real as food, and it deserves scheduled time.' },

  // ═══ ENNEAGRAM — 9 cores × happiness ═══
  { id: 'ennea:1:happiness', system: 'ennea', key: '1', domain: 'happiness', traitIds: ['enneagram:reformer-standards', 'enneagram:reformer-integrity'], text: 'Happiness for you is the rare moment when the inner critic falls silent and you feel that you — and the world around you — are good enough. You do not reach this state through lowering your standards but through meeting them and allowing the satisfaction to land. The practice: when you finish something well, forbid yourself from immediately noting what could be better. Sit with the completion for ten minutes. Your happiness exists in that gap between finishing and criticising.' },
  { id: 'ennea:2:happiness', system: 'ennea', key: '2', domain: 'happiness', traitIds: ['enneagram:helper-attunement', 'enneagram:helper-warmth'], text: 'Happiness for you is the feeling of being loved for who you are, not for what you give. This is also the feeling you have the hardest time believing is real. When someone offers you care without prompting, your instinct is to deflect or to immediately return the favour. The practice: receive one gift this week — a compliment, an invitation, a gesture of care — and say only "thank you." No deflection, no reciprocation for twenty-four hours. Let the love land.' },
  { id: 'ennea:3:happiness', system: 'ennea', key: '3', domain: 'happiness', traitIds: ['enneagram:achiever-drive', 'enneagram:achiever-image'], text: 'Happiness for you is the applause — the recognition that you did something exceptional. The standing ovation, the promotion, the client who said you changed everything. This is genuine pleasure, and there is nothing wrong with it. The risk: the applause ends and the happiness goes with it. The practice: find one form of happiness that has no witness. A private hobby, a journal entry, a walk where no one knows where you are. Your happiness needs a private room alongside its public stage.' },
  { id: 'ennea:4:happiness', system: 'ennea', key: '4', domain: 'happiness', traitIds: ['enneagram:individualist-depth', 'enneagram:individualist-longing'], text: 'Happiness for you is tinged with melancholy, and you would not have it any other way. A sunset, a poem, a moment of connection that you know will end — the beauty is inseparable from the impermanence. You are suspicious of simple happiness because it feels shallow. The practice: let yourself enjoy one uncomplicated pleasure this week without interrogating it for deeper meaning. Ice cream, a comedy, a sunny afternoon. Depth and lightness are not enemies; your happiness can hold both.' },
  { id: 'ennea:5:happiness', system: 'ennea', key: '5', domain: 'happiness', traitIds: ['enneagram:investigator-detach', 'enneagram:investigator-expertise'], text: 'Happiness for you is having all the information you need, a quiet room, and enough time to think without interruption. Your joy is cerebral and solitary, and there is nothing pathological about this. The world calls it isolation; you call it the best Tuesday afternoon imaginable. The risk: the need for solitude becomes a wall. The practice: share one discovery with one person this week. Your happiness deepens when the understanding you built alone is witnessed by someone who cares.' },
  { id: 'ennea:6:happiness', system: 'ennea', key: '6', domain: 'happiness', traitIds: ['enneagram:loyalist-vigilance', 'enneagram:loyalist-loyalty'], text: 'Happiness for you is safety — the bone-deep knowledge that the people you depend on are trustworthy and the ground beneath you is solid. You are happiest in established relationships, familiar environments, and roles where the expectations are clear. The risk: you equate happiness with the absence of anxiety, which means you never feel happy because the anxiety never fully stops. The practice: happiness and anxiety can coexist. Notice one moment today when both are present. That is not a failure — that is your version of joy.' },
  { id: 'ennea:7:happiness', system: 'ennea', key: '7', domain: 'happiness', traitIds: ['enneagram:enthusiast-optimism', 'enneagram:enthusiast-variety'], text: 'Happiness is your default orientation — you are pre-set to notice the bright side, to reframe the negative, and to generate enthusiasm from almost nothing. This is a genuine gift, and it is not superficial. The risk: you pursue happiness so aggressively that you avoid the experiences that would deepen it. Grief, loss, boredom, stillness — these are not the enemies of happiness; they are its depth charges. The practice: sit with one uncomfortable feeling for five minutes without reframing it. The happiness that follows will have roots.' },
  { id: 'ennea:8:happiness', system: 'ennea', key: '8', domain: 'happiness', traitIds: ['enneagram:challenger-directness', 'enneagram:challenger-protection'], text: 'Happiness for you is power used well. Not dominance — usefulness. When your strength protects someone, clears a path, or builds something that would not have existed without your force, you feel alive in a way that no vacation can replicate. The risk: you associate vulnerability with weakness and lock yourself out of the tenderness that happiness also requires. The practice: let someone see you soft. A child, a partner, a close friend. Happiness that includes tenderness is sturdier than happiness built on strength alone.' },
  { id: 'ennea:9:happiness', system: 'ennea', key: '9', domain: 'happiness', traitIds: ['enneagram:peacemaker-harmony', 'enneagram:peacemaker-numbing'], text: 'Happiness for you is peace — the absence of conflict, the presence of comfort, and the feeling that everything is, for this moment, enough. A sunny afternoon, a favourite show, a meal shared without argument. The risk: you settle for comfort and never discover the more intense happiness that comes from pursuing something you actually want. The practice: name one desire that is not about comfort. Not what you want for someone else — what you want for you. Your happiness has an active dimension that comfort alone does not activate.' },

  // ═══ HUMAN DESIGN — 5 types × happiness ═══
  { id: 'hd:Generator:happiness', system: 'hd', key: 'Generator', domain: 'happiness', traitIds: ['hd:sacral-energy'], text: 'Happiness for you is the sacral hum — that sustained, warm, buzzing energy you feel when you are doing work you genuinely responded to. It is physical, not conceptual. You know you are happy the way you know you are hungry: the body tells you. The practice: audit your week for sacral responses. Mark the activities that produced the hum and the ones that felt flat. Rearrange your schedule to increase the former. Your happiness is a measurable signal, not a philosophical question.' },
  { id: 'hd:Manifesting Generator:happiness', system: 'hd', key: 'Manifesting Generator', domain: 'happiness', traitIds: ['hd:multi-passionate'], text: 'Happiness for you is speed and variety. You are happiest when you are moving between interests, making progress on multiple fronts, and feeling the acceleration of a shortcut that actually works. Slowness is not peaceful for you — it is friction. The practice: build your life for speed, not for simplicity. Multiple projects, a fast-pivot schedule, and the permission to drop what stops pulling. Your happiness model is not minimalist; it is symphonic. Let it be.' },
  { id: 'hd:Projector:happiness', system: 'hd', key: 'Projector', domain: 'happiness', traitIds: ['hd:seeing-gift'], text: 'Happiness for you is recognition. Not applause — recognition. The moment when someone sees your gift, invites you to use it, and values the insight you offer. You are happiest in a focused burst of contribution followed by genuine rest. The practice: stop measuring your happiness by output volume. Measure it by depth of engagement and quality of rest. Three hours of deeply recognized work followed by an afternoon of nothing produces more happiness for your design than eight hours of unacknowledged effort.' },
  { id: 'hd:Manifestor:happiness', system: 'hd', key: 'Manifestor', domain: 'happiness', traitIds: ['hd:initiating-force'], text: 'Happiness is the unobstructed launch. You are happiest the moment you initiate — the business, the conversation, the creative act — and feel the world give way. Resistance dulls you, permission requests exhaust you, and waiting corrodes your mood. The practice: structure your life to initiate at least once per week. It does not need to be large. A new recipe, a rearranged room, a message you have been putting off. The act of beginning is your happiness mechanism; keep it exercised.' },
  { id: 'hd:Reflector:happiness', system: 'hd', key: 'Reflector', domain: 'happiness', traitIds: ['hd:mirror-quality'], text: 'Happiness for you is a reflection of your environment. In a healthy community, you glow. In a toxic one, you wilt. This is not weakness — it is design. Your happiness is the most accurate barometer of collective well-being in any group you belong to. The practice: choose your people before you choose your goals. The right community makes everything easier; the wrong one makes everything harder. Your happiness depends less on what you do than on who you do it among.' },

  // ═══ MILLMAN — finals 1–12 × happiness ═══
  { id: 'millman:1:happiness', system: 'millman', key: '1', domain: 'happiness', traitIds: ['millman:creative-independence'], text: 'Happiness on the 1 path arrives through creative expression completed despite self-doubt. You are happiest after you make something, not before. The anticipation is anxiety; the completion is relief and pride. The practice: finish one creative act per week. Small is fine. A letter, a drawing, a rearranged shelf. The act of completing something original is your happiness trigger, and it requires the discipline of starting.' },
  { id: 'millman:2:happiness', system: 'millman', key: '2', domain: 'happiness', traitIds: ['millman:cooperative-sensitivity'], text: 'Happiness on the 2 path is a partnership where giving and receiving are balanced. You are happiest when you feel useful and appreciated in equal measure. When the balance tips toward over-giving, resentment replaces joy silently. The practice: track one week of giving and receiving. Count the acts. If the ratio exceeds two to one in either direction, adjust. Your happiness is a balance sheet, and it needs honest accounting.' },
  { id: 'millman:3:happiness', system: 'millman', key: '3', domain: 'happiness', traitIds: ['millman:expressive-gift'], text: 'Happiness on the 3 path comes through speaking a truth that lands. You are happiest when your expression connects — when someone hears what you said and feels understood or moved. The inverse: suppressed expression becomes physical tension. The practice: say one emotionally honest thing per day to someone who matters. Not dramatic, not performative — honest. Your happiness is directly proportional to how much of your inner world you let out.' },
  { id: 'millman:4:happiness', system: 'millman', key: '4', domain: 'happiness', traitIds: ['millman:builder-persistence'], text: 'Happiness on the 4 path is the satisfaction of a long process yielding a stable result. You are happiest at the moment a foundation holds — the business survives its first year, the skill becomes reliable, the relationship proves its durability. The practice: identify one process you are in the middle of and acknowledge how far you have come. Your happiness lives in the accumulation, and you often forget to look back at what has already been built.' },
  { id: 'millman:5:happiness', system: 'millman', key: '5', domain: 'happiness', traitIds: ['millman:freedom-discipline'], text: 'Happiness on the 5 path is the experience of genuine freedom — not escape from responsibility but the capacity to choose your direction because your discipline has earned you that choice. You are happiest when you are free and competent simultaneously. The practice: identify one area where discipline has created freedom in your life and savour it deliberately. This is not indulgence — it is the recognition that your system is working.' },
  { id: 'millman:6:happiness', system: 'millman', key: '6', domain: 'happiness', traitIds: ['millman:visionary-standards'], text: 'Happiness on the 6 path is the moment when reality meets the vision, even partially. You are happiest when you see concrete evidence that things are getting better — not perfect, better. The practice: lower the resolution on your happiness criteria. Instead of waiting for the full picture to arrive, notice one pixel that is already in place. Your happiness is available now if you are willing to accept partial evidence.' },
  { id: 'millman:7:happiness', system: 'millman', key: '7', domain: 'happiness', traitIds: ['millman:inner-trust'], text: 'Happiness on the 7 path comes from trusting yourself and being proven right. The deep satisfaction of having followed your intuition against external advice and arriving at the correct destination. The practice: recall one moment when your gut was right and your advisors were wrong. Sit with that memory. Let it build the confidence that your inner knowing is a reliable source of happiness, not just a source of information.' },
  { id: 'millman:8:happiness', system: 'millman', key: '8', domain: 'happiness', traitIds: ['millman:abundant-leadership'], text: 'Happiness on the 8 path is abundance shared. You are happiest not when you accumulate but when the accumulation enables generosity — a dinner you hosted, a project you funded, a person you elevated. The practice: identify one form of abundance in your life and direct a portion of it outward this week. Money, time, attention, or skill. The flow itself is the pleasure; holding it still is not.' },
  { id: 'millman:9:happiness', system: 'millman', key: '9', domain: 'happiness', traitIds: ['millman:exemplar-integrity'], text: 'Happiness on the 9 path is alignment. You are happiest when your actions, your values, and your public identity are congruent. The moment you catch yourself saying one thing and doing another, happiness drains. The practice: identify one misalignment — however small — and correct it this week. Not for anyone else\'s sake, for your own. Your happiness is a direct function of your integrity, and integrity is maintained through small, continuous corrections.' },
  { id: 'millman:10:happiness', system: 'millman', key: '10', domain: 'happiness', traitIds: ['millman:creative-independence'], text: 'Happiness on the 10 path involves both personal creation and a sense of larger connection. You are happiest when something you made serves a purpose beyond yourself, however quietly. The practice: make one thing this week and offer it. A meal, a note, a repaired object. The double-digit energy of 10 asks that your creative happiness be shared, and sharing it completes the circuit.' },
  { id: 'millman:11:happiness', system: 'millman', key: '11', domain: 'happiness', traitIds: ['millman:creative-independence'], text: 'Happiness on the 11 path is the moment the paralysis breaks. You have been circling a creative act for days, doubting your right to make it, and then you sit down and make it anyway. The happiness is not in the product — it is in the act of defiance against the doubt. The practice: start before you are ready. The happiness of the 11 is always on the other side of the hesitation. Every time you begin despite the fear, you are happy for reasons the fear cannot reach.' },
  { id: 'millman:12:happiness', system: 'millman', key: '12', domain: 'happiness', traitIds: ['millman:creative-independence', 'millman:cooperative-sensitivity'], text: 'Happiness on the 12 path is co-creation. You are happiest when something you originated is made better by the people you invited into it. Neither the solo triumph nor the anonymous teamwork fully satisfies — you need both the pride of authorship and the warmth of collaboration. The practice: bring one personal creation to a trusted partner and ask them to add to it. The result will be better than either version, and the process is where your specific happiness lives.' },
];
