import type { CanonFragment } from './types';

/** Canon fragments — domain: relationships. */
export const RELATIONSHIPS_FRAGMENTS: CanonFragment[] = [
  // ═══ JUNG — 16 types × relationships ═══
  { id: 'jung:INTJ:relationships', system: 'jung', key: 'INTJ', domain: 'relationships', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'You love through competence and loyalty, not through verbal affirmation. You show care by solving problems, anticipating needs, and staying when it is hard. The people who understand this feel deeply loved. The people who need words feel neglected. The practice: translate your internal care into one explicit statement per week. "I thought about what you said" or "I noticed you were tired." You do not need to become expressive — you need to make the care you already carry briefly visible.' },
  { id: 'jung:INTP:relationships', system: 'jung', key: 'INTP', domain: 'relationships', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'You need a partner who respects your internal world and does not interpret silence as distance. Your love is shown in curiosity: you study the person you care about the way you study systems. The risk: you analyse the relationship instead of being in it. The practice: put the model down once a day and simply be present. Watch a film together, walk without talking, sit in the same room doing different things. Presence without analysis is a form of love your partner needs and your mind resists.' },
  { id: 'jung:ENTJ:relationships', system: 'jung', key: 'ENTJ', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'You approach relationships with the same strategic clarity you bring to work, which is both an asset and a liability. You are loyal, direct, and solution-oriented. The liability: you try to optimise your partner. People are not systems, and the feedback loop of "here is what you should improve" erodes intimacy faster than any neglect. The practice: listen to one complaint without offering a fix. Say "that sounds hard" and stop. The relationship needs your empathy as much as your efficiency.' },
  { id: 'jung:ENTP:relationships', system: 'jung', key: 'ENTP', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'You need a partner who can keep up with your mind and tolerate your restlessness. You love through play, debate, and shared exploration. The risk: you argue to think, but your partner hears the argument, not the thinking. The practice: preface intellectual sparring with "I am thinking out loud, not criticising." This single sentence prevents more damage than you imagine. Your love language is ideas; make sure the other person knows that is what they are receiving.' },
  { id: 'jung:INFJ:relationships', system: 'jung', key: 'INFJ', domain: 'relationships', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'You seek deep, soulful connection and have very little tolerance for superficial relating. When you find the person who meets you at depth, the bond is almost psychic. The risk: you idealise the bond and then feel betrayed when the real person falls short of the ideal. The practice: allow your partner to be ordinary sometimes. A moment of shallowness does not invalidate the depth. Relationships that last are built on the ability to tolerate banality between the transcendent moments.' },
  { id: 'jung:INFP:relationships', system: 'jung', key: 'INFP', domain: 'relationships', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'You love deeply, quietly, and with a faithfulness that few types match. You see your partner\'s potential as clearly as their reality, and you hold both with care. The risk: you project so much beauty onto the person that they can never live up to your inner image of them. The practice: love the real person, including the parts that disappoint. Disappointment in a relationship is not a sign that love has failed — it is a sign that fantasy has given way to intimacy, which is harder and more valuable.' },
  { id: 'jung:ENFJ:relationships', system: 'jung', key: 'ENFJ', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'You are the most devoted partner in the typology. You study your person, anticipate their needs, and create environments where they flourish. The cost: you lose yourself. Your needs become invisible behind your attentiveness. The practice: state one need out loud this week. Not a request disguised as a suggestion — a need. "I need time alone tonight" or "I need you to ask about my day." The relationship becomes more honest the moment you stop curating your partner\'s experience and start expressing your own.' },
  { id: 'jung:ENFP:relationships', system: 'jung', key: 'ENFP', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'You fall in love with potential. The first weeks of a relationship are intoxicating because everything is possibility. The risk: when the reality of the person replaces the possibility, you lose interest and begin scanning for the next spark. The practice: when the novelty fades, investigate what remains instead of what has disappeared. Long love is not a sustained high — it is a deepening familiarity that offers pleasures the spark never could. Stay for one season past the fade and see what grows.' },
  { id: 'jung:ISTJ:relationships', system: 'jung', key: 'ISTJ', domain: 'relationships', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'You love through consistency. You show up, you remember, you follow through. Your love is expressed in actions, not words, and the people who understand this feel profoundly safe with you. The risk: consistency without warmth becomes duty, and duty without affection is a cage. The practice: add one unexpected gesture per month. A note, a gift, an unprompted compliment. Not because your love needs proving — because your partner needs to feel it in a language that is not only structural.' },
  { id: 'jung:ISFJ:relationships', system: 'jung', key: 'ISFJ', domain: 'relationships', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'You create a home in the emotional sense — a space where people feel cared for, remembered, and protected. You track the details of the people you love with extraordinary precision: their preferences, their fears, their comfort foods. The risk: you give without boundary and then feel invisible. The practice: share one thing about yourself that your partner does not know. Vulnerability in the direction of self-disclosure is your growing edge. The relationship deepens when you are seen, not only when you see.' },
  { id: 'jung:ESTJ:relationships', system: 'jung', key: 'ESTJ', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'You bring structure and reliability to a relationship. Plans are kept, finances are managed, responsibilities are clear. Your partner always knows where they stand with you, which is a genuine form of love. The risk: you manage the relationship like a project and forget that your partner is not a direct report. The practice: ask "how are you feeling?" and then sit with the answer without solving it. Emotional presence is a skill you can learn, and it transforms functional relationships into intimate ones.' },
  { id: 'jung:ESFJ:relationships', system: 'jung', key: 'ESFJ', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'You love generously and visibly. Your partner is cared for, celebrated, and never forgotten. You track anniversaries, plan surprises, and maintain the social fabric around the relationship with tireless energy. The risk: you need appreciation in return and feel devastated when it does not come at the level you give. The practice: tell your partner what you need. Not in the hope they will guess — directly. "I need you to notice what I did" is not needy; it is honest. Your love has a return address; use it.' },
  { id: 'jung:ISTP:relationships', system: 'jung', key: 'ISTP', domain: 'relationships', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'You love through action and presence. You fix the thing that is broken, you drive when it is raining, you stay calm in the crisis. Verbal affirmation is not your language, and emotional processing is not your comfort zone. The risk: your partner interprets your silence as indifference. The practice: bridge the gap with one small narration per day. "I repaired the shelf because you mentioned it bothered you" connects the action to the care. You do not need to become sentimental — you need to narrate the love that is already in motion.' },
  { id: 'jung:ISFP:relationships', system: 'jung', key: 'ISFP', domain: 'relationships', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'You love through presence and small acts of beauty. A flower left on the table, a meal made with care, a hand held at the right moment. Your love is understated and deeply felt, and the people who receive it know it is rare. The risk: you absorb your partner\'s emotions without filter and lose your own centre. The practice: check your emotional state before and after time with your partner. If the gap is large, the boundary needs tending. Your love is sustainable only when your own ground is firm.' },
  { id: 'jung:ESTP:relationships', system: 'jung', key: 'ESTP', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'You love through experience. Adventures, challenges, physical affection, and shared intensity are your love languages. You are at your most attractive when you are fully alive, and you need a partner who can match your energy or at least not resent it. The risk: you avoid the slow, emotional conversations that deepen a bond. The practice: sit with one emotional topic for ten minutes without deflecting into humour or action. The discomfort is the growth, and the growth is what turns attraction into attachment.' },
  { id: 'jung:ESFP:relationships', system: 'jung', key: 'ESFP', domain: 'relationships', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'You love by making life fun. Your partner gets surprise dates, spontaneous affection, and the feeling that every day could hold something delightful. You are generous, warm, and physically expressive. The risk: when the relationship requires sustained seriousness — grief, financial stress, long-distance — your instinct is to lighten it, and your partner needs you to stay heavy. The practice: in the next hard moment, resist the urge to cheer. Say "I am here" and sit with the weight. Your partner needs your presence more than your brightness.' },

  // ═══ ENNEAGRAM — 9 cores × relationships ═══
  { id: 'ennea:1:relationships', system: 'ennea', key: '1', domain: 'relationships', traitIds: ['enneagram:reformer-standards', 'enneagram:reformer-critic'], text: 'You hold your partner to the same standard you hold yourself, which is very high and rarely satisfied. Your love is expressed as improvement: you correct because you care. The cost: your partner feels judged instead of loved. The practice: before you offer a correction, offer an appreciation. Not as a technique — as a genuine acknowledgment that the person you love is already doing many things right. The ratio of appreciation to correction determines whether your care lands as love or as audit.' },
  { id: 'ennea:2:relationships', system: 'ennea', key: '2', domain: 'relationships', traitIds: ['enneagram:helper-attunement', 'enneagram:helper-giving'], text: 'You give in order to be loved, and the giving is so instinctive that you rarely see the transaction beneath it. Your partner receives attentive, anticipatory care. The cost: you accumulate invisible IOUs and feel betrayed when they are not repaid. The practice: give one thing this week with genuinely no expectation of return. Notice how that feels different. The shift from transactional giving to free giving is the deepest work of the Two in love.' },
  { id: 'ennea:3:relationships', system: 'ennea', key: '3', domain: 'relationships', traitIds: ['enneagram:achiever-drive', 'enneagram:achiever-adapt'], text: 'You adapt to be lovable. With each new partner, a slightly different version of you appears — the one you believe they will admire. This works until the relationship deepens and your partner asks to see the real you. The practice: show one unpolished truth this week. An insecurity, a failure, a desire you are ashamed of. Intimacy is built on being known, not on being impressive. The relationship you want requires the person you actually are, not the person you perform.' },
  { id: 'ennea:4:relationships', system: 'ennea', key: '4', domain: 'relationships', traitIds: ['enneagram:individualist-depth', 'enneagram:individualist-longing'], text: 'You long for a love that matches the intensity of your inner world. When you find it, you test it — pushing and pulling to see if it can withstand the pressure. The relationship becomes a drama because ordinary love feels insufficient. The practice: notice when you are manufacturing intensity to feel alive. Stability is not boredom — it is the ground from which real depth grows. Let the relationship be quiet for a week and see what emerges in the silence.' },
  { id: 'ennea:5:relationships', system: 'ennea', key: '5', domain: 'relationships', traitIds: ['enneagram:investigator-detach', 'enneagram:investigator-conserve'], text: 'You love from a distance that others find confusing. Your affection is real but rationed — you give deeply in controlled doses and then withdraw to restore. Your partner may feel intermittently abandoned. The practice: name the withdrawal before it happens. "I need two hours alone, and I will come back." This simple sentence turns abandonment into a rhythm your partner can trust. Your love requires boundaries; boundaries require narration.' },
  { id: 'ennea:6:relationships', system: 'ennea', key: '6', domain: 'relationships', traitIds: ['enneagram:loyalist-vigilance', 'enneagram:loyalist-loyalty'], text: 'Once you trust someone, your loyalty is total. You protect the relationship with the same vigilance you apply to threats. The cost: you test your partner\'s loyalty by imagining betrayals and then reading innocent behaviour as evidence. The practice: when suspicion arises, state it as a question rather than an accusation. "Can you help me understand why you were late?" invites truth. "Where were you really?" invites defence. Your relationship improves the moment you replace testing with asking.' },
  { id: 'ennea:7:relationships', system: 'ennea', key: '7', domain: 'relationships', traitIds: ['enneagram:enthusiast-optimism', 'enneagram:enthusiast-avoidance'], text: 'You bring adventure, optimism, and a refusal to be bored into every relationship. Your partner gets spontaneity, ideas, and the feeling that anything is possible. The cost: when the relationship requires you to sit with pain — theirs or yours — you reach for the escape hatch. A joke, a plan, a distraction. The practice: the next time your partner is in pain, cancel every impulse except one: stay. Sit with the difficulty for twenty minutes without fixing or reframing it. That presence is worth more than any adventure.' },
  { id: 'ennea:8:relationships', system: 'ennea', key: '8', domain: 'relationships', traitIds: ['enneagram:challenger-directness', 'enneagram:challenger-control'], text: 'You love fiercely and protectively. The people inside your circle receive your full force in their defence. The cost: you control the relationship to prevent vulnerability, and control is the opposite of intimacy. The practice: let your partner make one decision this week that you disagree with. Do not intervene, advise, or manoeuvre. Let the outcome happen. Trust in a relationship is built when you allow the other person to be wrong without catching them. Your strength includes the ability to step back.' },
  { id: 'ennea:9:relationships', system: 'ennea', key: '9', domain: 'relationships', traitIds: ['enneagram:peacemaker-harmony', 'enneagram:peacemaker-merging'], text: 'You merge with your partner. Their preferences become yours, their moods become yours, and after a while neither of you can tell where one ends and the other begins. This feels like intimacy; it is actually the absence of two distinct people. The practice: disagree about something small this week. Not to fight — to demonstrate that two different humans occupy this relationship. Your partner needs to know you exist as a separate person. Otherwise they are in love with an echo, and echoes do not satisfy.' },

  // ═══ HUMAN DESIGN — 5 types × relationships ═══
  { id: 'hd:Generator:relationships', system: 'hd', key: 'Generator', domain: 'relationships', traitIds: ['hd:sacral-energy'], text: 'Your sacral responds to people the same way it responds to work: with a full-body yes or a flat nothing. Trust that response. When you feel the pull toward someone, the energy is real and sustainable. When you force a connection your body did not choose, the relationship drains you exactly the way wrong work does. The practice: before you commit further, check your gut. Not your mind\'s analysis, not your heart\'s hope — the body\'s signal. That is the instrument your design gave you for relationships.' },
  { id: 'hd:Manifesting Generator:relationships', system: 'hd', key: 'Manifesting Generator', domain: 'relationships', traitIds: ['hd:multi-passionate'], text: 'You need a partner who can handle your speed, your pivots, and your simultaneous interests. A relationship that requires you to slow down permanently will fail — not because of insufficient love but because of incompatible rhythm. The practice: communicate your tempo early. "I move fast and change direction" is not a warning — it is an invitation for the right person and a kindness to the wrong one. Relationships that match your speed become exhilarating; relationships that resist it become exhausting.' },
  { id: 'hd:Projector:relationships', system: 'hd', key: 'Projector', domain: 'relationships', traitIds: ['hd:seeing-gift'], text: 'You see your partner with painful clarity — their patterns, their potential, their blind spots. Uninvited, this insight feels like surveillance. Invited, it feels like being truly known. The practice: wait for the question. When your partner asks "what do you think?", give the full read. When they do not ask, hold it. The discipline of waiting transforms your insight from intrusion into gift. Your relationships improve the moment you separate seeing from speaking.' },
  { id: 'hd:Manifestor:relationships', system: 'hd', key: 'Manifestor', domain: 'relationships', traitIds: ['hd:initiating-force'], text: 'You value independence above almost everything, and relationships that limit it become prisons regardless of the love inside them. Your partner must understand that your need for space is not rejection — it is design. The practice: inform before you withdraw. "I need the evening alone" is a relationship-saving sentence. Your partner can handle your independence when it is narrated; they cannot handle it when it feels like abandonment. The difference is one sentence.' },
  { id: 'hd:Reflector:relationships', system: 'hd', key: 'Reflector', domain: 'relationships', traitIds: ['hd:mirror-quality'], text: 'You become a different version of yourself with each partner because you absorb and reflect their energy. This is not inauthenticity — it is your design. The risk: you lose track of who you are underneath the reflection. The practice: spend time alone between relational encounters and notice what remains when the other person\'s influence fades. The consistent core beneath the fluctuation is you. Relationships that work for your design are ones where you feel most yourself, not least.' },

  // ═══ MILLMAN — finals 1–12 × relationships ═══
  { id: 'millman:1:relationships', system: 'millman', key: '1', domain: 'relationships', traitIds: ['millman:creative-independence'], text: 'Your path asks for independence, and relationships are where this gets complicated. You need a partner who loves your originality without trying to domesticate it. The practice: communicate one non-negotiable boundary early. Not as a wall — as information. "I need creative solitude and it is not about you" prevents the misunderstanding that later destroys.' },
  { id: 'millman:2:relationships', system: 'millman', key: '2', domain: 'relationships', traitIds: ['millman:cooperative-sensitivity'], text: 'Relationships are your curriculum. You are here to learn the difference between codependence and genuine partnership. Every relationship you enter will teach you something about boundaries — often the hard way. The practice: define one expectation before the next conflict arrives. Write it down. Boundaries established in advance are contracts; boundaries established in anger are walls.' },
  { id: 'millman:3:relationships', system: 'millman', key: '3', domain: 'relationships', traitIds: ['millman:expressive-gift'], text: 'Expression is your love language. You need a partner who listens — really listens — and gives you space to articulate what you feel. A relationship where you suppress your voice to keep the peace will slowly destroy you. The practice: say the hard thing early. Your path demands that you speak truth in intimate spaces. The relationship that survives your honesty is the one worth keeping.' },
  { id: 'millman:4:relationships', system: 'millman', key: '4', domain: 'relationships', traitIds: ['millman:builder-persistence'], text: 'You build relationships slowly and they last. Quick attachments are not your design — you need time, process, and evidence before you commit. The practice: resist the pressure to accelerate. A partner who cannot wait for your trust is not the partner who deserves it. Your relationships are built like your work: stone by stone, with each layer tested before the next is laid.' },
  { id: 'millman:5:relationships', system: 'millman', key: '5', domain: 'relationships', traitIds: ['millman:freedom-discipline'], text: 'You need freedom within your relationship, and you earn it by being reliable in the areas your partner cares about. Freedom without reliability is selfishness; reliability without freedom is a cage. The practice: identify the commitments your partner considers non-negotiable and honour them completely. From that base, your request for space becomes trustworthy.' },
  { id: 'millman:6:relationships', system: 'millman', key: '6', domain: 'relationships', traitIds: ['millman:visionary-standards'], text: 'You see who your partner could be, and the gap between potential and reality is a source of silent frustration. Your love is aspirational — which is both motivating and exhausting for the person receiving it. The practice: love the person in front of you, not the improved version in your mind. Tell them what you appreciate about who they are now, without appending what they could become.' },
  { id: 'millman:7:relationships', system: 'millman', key: '7', domain: 'relationships', traitIds: ['millman:inner-trust'], text: 'You sense relational truth before you can prove it. You know when something is off, and you know when someone is right, often within minutes. The challenge: trusting that sense against contrary evidence. The practice: when your gut says something about a person, honour it. Not as certainty — as data. Your intuition in relationships is more accurate than your analysis. Let it lead.' },
  { id: 'millman:8:relationships', system: 'millman', key: '8', domain: 'relationships', traitIds: ['millman:abundant-leadership'], text: 'You bring authority and abundance to relationships — generosity, protection, and a commanding presence. The risk: you dominate. The practice: ask your partner "what do you want?" and then listen without immediately reshaping the answer into your plan. Your love is powerful; power that includes listening becomes partnership. Power that only speaks becomes dictatorship, however benevolent.' },
  { id: 'millman:9:relationships', system: 'millman', key: '9', domain: 'relationships', traitIds: ['millman:exemplar-integrity'], text: 'You hold yourself to a high standard in relationships, and your partner watches you more than you realise. When you break your own rules, the trust erodes quietly. The practice: align one relationship behaviour with your stated values this week. If you say honesty matters, share one difficult truth. If you say presence matters, put the phone down. Your partner trusts your actions, not your principles.' },
  { id: 'millman:10:relationships', system: 'millman', key: '10', domain: 'relationships', traitIds: ['millman:creative-independence'], text: 'Your path connects creative individuality to the broader picture. In relationships, this means you need a partner who honours your originality while sharing a larger vision. The practice: identify one shared goal that is bigger than both of you and work toward it together. The 10 path in relationships is fulfilled when personal expression serves a joint purpose.' },
  { id: 'millman:11:relationships', system: 'millman', key: '11', domain: 'relationships', traitIds: ['millman:creative-independence'], text: 'The doubled creative energy brings intensity to relationships — both the intensity of connection and the intensity of doubt. You question whether you deserve the love you receive, and this doubt creates distance. The practice: when the doubt whispers "they will leave," answer it out loud to your partner. "I am afraid you will leave" is vulnerable, and vulnerability is the antidote to the 11\'s self-sabotage in love.' },
  { id: 'millman:12:relationships', system: 'millman', key: '12', domain: 'relationships', traitIds: ['millman:creative-independence', 'millman:cooperative-sensitivity'], text: 'Your path asks for a relationship that is both deeply personal and genuinely collaborative. You need a partner who is a co-creator, not just a companion. The practice: build something together — a project, a home, a tradition. The 12 path in love is walked not side by side but hand in hand, making something that neither person could make alone.' },
];
