import type { CanonFragment } from './types';

/** Canon fragments — domain: growth. */
export const GROWTH_FRAGMENTS: CanonFragment[] = [
  // ═══ JUNG — 16 types × growth ═══
  { id: 'jung:INTJ:growth', system: 'jung', key: 'INTJ', domain: 'growth', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Your growth edge is emotional intelligence. Not emotional expression — emotional intelligence: the ability to read, name, and respond to feelings in yourself and others without dismissing them as irrational data. The practice: when someone shares an emotion, resist the impulse to solve it. Ask "what do you need right now?" and listen. This single question exercises the muscle your type neglects most.' },
  { id: 'jung:INTP:growth', system: 'jung', key: 'INTP', domain: 'growth', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Your growth edge is completion. You begin with brilliance and stall at execution. The gap between your ideas and your output is the distance your development needs to cross. The practice: finish one thing this week that has been sitting at eighty percent. Not perfectly — completely. The act of shipping teaches your system that completion is safe, and repetition of that lesson changes your career more than any new framework.' },
  { id: 'jung:ENTJ:growth', system: 'jung', key: 'ENTJ', domain: 'growth', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Your growth edge is receptivity. You lead naturally, decide quickly, and direct forcefully. The capacity you have not developed is the one that listens without planning, receives without judging, and waits without acting. The practice: spend one conversation per week in pure listening mode. No agenda, no follow-up actions, no mental list of what the other person should do differently. This is harder for you than any strategic challenge, and that difficulty is the point.' },
  { id: 'jung:ENTP:growth', system: 'jung', key: 'ENTP', domain: 'growth', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Your growth edge is depth. You are the master of breadth — connecting ideas across domains, generating options, seeing possibilities. What you resist is the sustained, single-pointed attention that turns a good idea into a great one. The practice: choose one interest and spend thirty days going deeper instead of wider. Read the second book on the topic, not the first book on a new one. Your genius broadens naturally; it deepens only through discipline.' },
  { id: 'jung:INFJ:growth', system: 'jung', key: 'INFJ', domain: 'growth', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Your growth edge is self-assertion. You see others\' needs with extraordinary clarity and your own with studied vagueness. You advocate for the world and forget to advocate for yourself. The practice: state one need this week without wrapping it in someone else\'s context. Not "I think the team would benefit from X" — just "I need X." The directness will feel selfish. It is not. It is the beginning of a self that others can meet as an equal, not only as a caretaker.' },
  { id: 'jung:INFP:growth', system: 'jung', key: 'INFP', domain: 'growth', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Your growth edge is action. Your inner world is rich, nuanced, and fully developed. Your outer world often lags behind because translating internal clarity into external movement feels reductive. The practice: take one idea you have been carrying and give it a form this week. Write it, say it, build it. The translation will be imperfect, and the imperfection is the growth. Your inner world serves you; your growth begins when it serves others through action.' },
  { id: 'jung:ENFJ:growth', system: 'jung', key: 'ENFJ', domain: 'growth', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Your growth edge is selfishness — used here without moral charge, as the simple act of placing your own development above service to others. You grow by withdrawing your attention from others long enough to ask what you actually need. The practice: cancel one obligation this week and spend the time on something that serves only you. The discomfort you feel is the development itself. You are learning that self-care is not betrayal.' },
  { id: 'jung:ENFP:growth', system: 'jung', key: 'ENFP', domain: 'growth', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Your growth edge is follow-through. You initiate with brilliance and lose momentum at the midpoint. The unsexy, repetitive middle of every project is where your development happens. The practice: choose one current project and commit to working on it for fifteen minutes every day for thirty days. Not the exciting part — the boring part. The habit of persistence, once installed, changes everything that follows.' },
  { id: 'jung:ISTJ:growth', system: 'jung', key: 'ISTJ', domain: 'growth', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Your growth edge is flexibility. You have built your life on structure, and it serves you well. The development comes from learning that some structures can be loosened without collapsing. The practice: change one routine this week. Take a different route, eat at a different time, approach a problem without a plan. The goal is not chaos — it is the discovery that you can adapt without losing your foundation.' },
  { id: 'jung:ISFJ:growth', system: 'jung', key: 'ISFJ', domain: 'growth', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Your growth edge is self-expression. You have spent your life tuning your antenna to others\' needs. The developmental task is turning it toward yourself. The practice: complete this sentence daily for one week: "Today I want ____." Not "today I should" or "today they need" — "today I want." The answers may surprise you. They have been waiting for this question your entire life.' },
  { id: 'jung:ESTJ:growth', system: 'jung', key: 'ESTJ', domain: 'growth', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Your growth edge is vulnerability. You lead through competence, and any admission of uncertainty feels like a structural crack. But the people around you connect more deeply with your humanity than with your efficiency. The practice: share one thing you are uncertain about with someone you trust. "I do not know how to handle this" is not weakness — it is the beginning of the kind of leadership that inspires, rather than merely organises.' },
  { id: 'jung:ESFJ:growth', system: 'jung', key: 'ESFJ', domain: 'growth', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Your growth edge is independence of opinion. You calibrate to the group instinctively, and the developmental work is learning to hold a position that the group does not share. The practice: form an opinion on a current topic before consulting anyone. Write it down. Then discuss it. Notice whether and how the opinion shifts under social influence. The awareness itself is the growth; you do not need to become contrarian, just conscious.' },
  { id: 'jung:ISTP:growth', system: 'jung', key: 'ISTP', domain: 'growth', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Your growth edge is emotional vocabulary. You feel things; you do not name them. The gap between the internal experience and the capacity to articulate it creates distance in every relationship you enter. The practice: once per day, name what you are feeling with one word. Not "fine." An actual feeling: frustrated, content, restless, grateful. The naming does not change the feeling; it makes it available to the people who care about you.' },
  { id: 'jung:ISFP:growth', system: 'jung', key: 'ISFP', domain: 'growth', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Your growth edge is visibility. You do beautiful work and then let it disappear. You help people and then deflect the credit. The developmental task is learning to be seen. The practice: share one piece of your work publicly this week. A photo, a thought, a creation. Not for validation — for the practice of occupying space. Your growth begins the moment your gifts stop being invisible.' },
  { id: 'jung:ESTP:growth', system: 'jung', key: 'ESTP', domain: 'growth', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Your growth edge is patience. You act first and reflect never. The developmental capacity you need is the ability to pause between impulse and action — not to eliminate the impulse, but to choose which ones deserve execution. The practice: before your next significant decision, wait twenty-four hours. Not to deliberate endlessly — just to let one sleep cycle separate the impulse from the commitment. The decisions that survive the night are the ones worth making.' },
  { id: 'jung:ESFP:growth', system: 'jung', key: 'ESFP', domain: 'growth', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Your growth edge is depth. You live brilliantly in the present moment, and the developmental work is learning to sustain attention on things that do not offer immediate reward. The practice: read one long article per week on a topic that does not entertain you. Finish it. The capacity to engage with what is not immediately pleasant is the muscle that, once built, gives your spontaneity a foundation it cannot have without effort.' },

  // ═══ ENNEAGRAM — 9 cores × growth ═══
  { id: 'ennea:1:growth', system: 'ennea', key: '1', domain: 'growth', traitIds: ['enneagram:reformer-standards', 'enneagram:reformer-integrity'], text: 'Your growth direction is toward acceptance — not lowering your standards but widening your capacity to tolerate imperfection. The practice: identify one thing this week that is "good enough" and let it stay that way. The inner critic will object. Let it object while you move on. Growth for the One is not the elimination of standards; it is the development of mercy alongside them.' },
  { id: 'ennea:2:growth', system: 'ennea', key: '2', domain: 'growth', traitIds: ['enneagram:helper-attunement', 'enneagram:helper-giving'], text: 'Your growth direction is toward self-awareness of your own needs. You have spent your life tracking what others need; the developmental work is turning that radar inward. The practice: three times today, stop and ask "what do I need right now?" — before anyone else\'s needs enter the picture. This is not selfish. It is the foundation that makes your generosity sustainable instead of depleting.' },
  { id: 'ennea:3:growth', system: 'ennea', key: '3', domain: 'growth', traitIds: ['enneagram:achiever-drive', 'enneagram:achiever-adapt'], text: 'Your growth direction is toward authenticity — the discovery that you are valuable without the achievement. The practice: spend one hour in a context where no one knows your resume. A new class, a community event, a conversation with a stranger. Notice who you are when the performance scaffolding is removed. The person who remains is the one your development is trying to introduce you to.' },
  { id: 'ennea:4:growth', system: 'ennea', key: '4', domain: 'growth', traitIds: ['enneagram:individualist-depth', 'enneagram:individualist-unique'], text: 'Your growth direction is toward equanimity — the capacity to maintain emotional balance without numbing the feeling. You feel everything at full volume; the developmental work is not turning it down but building a container large enough to hold it. The practice: when a strong emotion arrives, notice it without narrating it. "Sadness is here" rather than the story of why. The feeling itself is information; the story is optional.' },
  { id: 'ennea:5:growth', system: 'ennea', key: '5', domain: 'growth', traitIds: ['enneagram:investigator-detach', 'enneagram:investigator-conserve'], text: 'Your growth direction is toward engagement. You have perfected observation; the developmental work is participation. The practice: join one activity this month that requires you to be present in your body, not just your mind. A dance class, a cooking group, a team sport. The discomfort of physical participation is exactly the growth edge your type avoids and most needs.' },
  { id: 'ennea:6:growth', system: 'ennea', key: '6', domain: 'growth', traitIds: ['enneagram:loyalist-vigilance', 'enneagram:loyalist-loyalty'], text: 'Your growth direction is toward courage — not the absence of fear but the capacity to act while afraid. The practice: do one thing this week that your anxiety advises against, provided it is physically safe and ethically sound. Ask for the raise, have the conversation, make the call. Each small act of courage despite fear rewires the relationship between vigilance and action. You do not need to eliminate the fear; you need to prove it does not govern you.' },
  { id: 'ennea:7:growth', system: 'ennea', key: '7', domain: 'growth', traitIds: ['enneagram:enthusiast-optimism', 'enneagram:enthusiast-avoidance'], text: 'Your growth direction is toward sobriety — the capacity to sit with what is, including what is painful, without escaping into what could be. The practice: when discomfort arrives today, stay with it for five minutes before you plan, reframe, or distract. Notice what the discomfort is actually telling you. The information available in that five minutes is the growth your type routinely skips. It is waiting for you in the stillness.' },
  { id: 'ennea:8:growth', system: 'ennea', key: '8', domain: 'growth', traitIds: ['enneagram:challenger-directness', 'enneagram:challenger-protection'], text: 'Your growth direction is toward vulnerability — the discovery that strength includes the capacity to be seen in weakness. The practice: share one fear or uncertainty with someone you trust this week. Not wrapped in bravado, not followed by a plan to fix it — just the raw admission. The trust this builds is deeper than the trust earned through strength alone. Your growth is not about becoming softer; it is about showing what is already soft beneath the armour.' },
  { id: 'ennea:9:growth', system: 'ennea', key: '9', domain: 'growth', traitIds: ['enneagram:peacemaker-harmony', 'enneagram:peacemaker-numbing'], text: 'Your growth direction is toward activation — the capacity to want something strongly enough to disrupt your own comfort. The practice: name one thing you want and take one step toward it today. The step does not need to be large; it needs to be yours. Your development begins the moment you act on your own desire instead of accommodating someone else\'s. Comfort is not the enemy; complacency is.' },

  // ═══ HUMAN DESIGN — 5 types × growth ═══
  { id: 'hd:Generator:growth', system: 'hd', key: 'Generator', domain: 'growth', traitIds: ['hd:sacral-energy'], text: 'Your growth is in refining the sacral response. You have the energy; the development is in trusting which direction it wants to go. The practice: each morning, present yourself with two options and notice which one produces a body-level response. Not a mental preference — a physical pull. Training this sense is your lifelong developmental work. It gets more accurate with use, not with thought.' },
  { id: 'hd:Manifesting Generator:growth', system: 'hd', key: 'Manifesting Generator', domain: 'growth', traitIds: ['hd:multi-passionate'], text: 'Your growth is in learning to inform. You move so fast that others are left in your wake, confused and excluded. The developmental practice: narrate your pivots. "I was doing A, it stopped working, I am now on B" takes five seconds and transforms your speed from chaos into leadership. Your growth is not about slowing down — it is about making your speed legible to the people who travel with you.' },
  { id: 'hd:Projector:growth', system: 'hd', key: 'Projector', domain: 'growth', traitIds: ['hd:seeing-gift'], text: 'Your growth is in learning to wait for the invitation without losing confidence during the wait. The gap between your readiness and the world\'s recognition is your developmental crucible. The practice: use the waiting time to refine your gift. Study, practice, deepen your expertise. When the invitation comes — and it will — the depth you built in the waiting becomes your authority. The wait is not waste; it is preparation.' },
  { id: 'hd:Manifestor:growth', system: 'hd', key: 'Manifestor', domain: 'growth', traitIds: ['hd:initiating-force'], text: 'Your growth is in learning that informing is not the same as asking permission. Your design initiates; the developmental work is doing so with enough narration that the people affected are not blindsided. The practice: before your next initiation, send one message: "I am going to do X." Not "may I" — "I am going to." The growth is in the tension between your autonomy and your impact on others. Both are real; both matter.' },
  { id: 'hd:Reflector:growth', system: 'hd', key: 'Reflector', domain: 'growth', traitIds: ['hd:mirror-quality'], text: 'Your growth is in learning to distinguish your feelings from the environment\'s feelings. The practice: at the end of each day, sit alone for ten minutes and ask "what remains?" What fades was the field; what remains is you. Over time, this practice builds an increasingly clear sense of your own centre — the one stable point in a design that is built to fluctuate. That centre is your growth and your gift.' },

  // ═══ MILLMAN — finals 1–12 × growth ═══
  { id: 'millman:1:growth', system: 'millman', key: '1', domain: 'growth', traitIds: ['millman:creative-independence'], text: 'Your growth is in moving from self-doubt to creative confidence, not by eliminating the doubt but by creating in its presence. The practice: make one thing today despite the voice that says you should not. The doubt is not going away. Your growth is the relationship you build with it — adversarial at first, then coexistent, eventually almost companionable.' },
  { id: 'millman:2:growth', system: 'millman', key: '2', domain: 'growth', traitIds: ['millman:cooperative-sensitivity'], text: 'Your growth is in learning boundaries without losing empathy. Not walls — boundaries. The difference: walls block everything; boundaries filter. The practice: say no to one request this week that you would normally accept on reflex. Notice what happens. The relationship survives, your energy returns, and your growth in discernment begins.' },
  { id: 'millman:3:growth', system: 'millman', key: '3', domain: 'growth', traitIds: ['millman:expressive-gift'], text: 'Your growth is in moving from performance to authenticity. You express naturally; the developmental work is expressing what is true rather than what is impressive. The practice: share one thing this week that is not polished, not rehearsed, and not designed to earn admiration. The vulnerability of imperfect expression is your growth edge. What lands honestly lands deeper than what lands eloquently.' },
  { id: 'millman:4:growth', system: 'millman', key: '4', domain: 'growth', traitIds: ['millman:builder-persistence'], text: 'Your growth is in trusting the process when the result is not yet visible. You build well, but impatience with the timeline creates unnecessary suffering. The practice: acknowledge one step you completed this week and resist the urge to immediately look at the steps remaining. Your growth is in letting a finished step count as ground gained, even while the building stands incomplete.' },
  { id: 'millman:5:growth', system: 'millman', key: '5', domain: 'growth', traitIds: ['millman:freedom-discipline'], text: 'Your growth is in discovering that discipline and freedom are the same thing viewed from different angles. The practice: sustain one discipline for sixty consecutive days. Notice the freedom that emerges on the other side. Your growth is in this discovery: the cage you resisted was never the discipline. It was the resistance.' },
  { id: 'millman:6:growth', system: 'millman', key: '6', domain: 'growth', traitIds: ['millman:visionary-standards'], text: 'Your growth is in learning to see what is, not only what could be. Acceptance is your practice, and it does not mean surrender. The practice: find one thing today that is exactly right, exactly as it is, requiring no improvement. Sit with it. Your visionary gift matures when it learns to appreciate the present alongside the future.' },
  { id: 'millman:7:growth', system: 'millman', key: '7', domain: 'growth', traitIds: ['millman:inner-trust'], text: 'Your growth is in trusting your inner knowing even when you cannot explain it. The practice: act on one intuitive impulse this week without building a rational case for it. Tell no one why. Track the result. The growth of the 7 path is the gradual, evidence-based construction of faith in an instrument that does not produce evidence on demand.' },
  { id: 'millman:8:growth', system: 'millman', key: '8', domain: 'growth', traitIds: ['millman:abundant-leadership'], text: 'Your growth is in learning that power shared is power multiplied. Holding every decision yourself feels safe and quietly caps everything you build at the size of one person. The practice: delegate one responsibility this week that you could do better yourself, and let the result stand imperfect. What you lose in polish you gain in people who can carry weight beside you — and that is the larger abundance the 8 path is actually about.' },
  { id: 'millman:9:growth', system: 'millman', key: '9', domain: 'growth', traitIds: ['millman:exemplar-integrity'], text: 'Your growth is in forgiving yourself for the moments you fell short of your own standard. Integrity does not require perfection; it requires honest recovery. The practice: identify one recent failure and instead of self-punishment, ask what it taught you. Your growth includes mercy toward yourself, not only standards for yourself.' },
  { id: 'millman:10:growth', system: 'millman', key: '10', domain: 'growth', traitIds: ['millman:creative-independence'], text: 'Your growth is in learning that endings are beginnings. The zero in your path carries the energy of completion and renewal. The practice: identify one thing that has ended — a project, a phase, a relationship — and acknowledge the ending explicitly. Your growth occurs in the space between what was and what comes next, not in rushing to fill it.' },
  { id: 'millman:11:growth', system: 'millman', key: '11', domain: 'growth', traitIds: ['millman:creative-independence'], text: 'Your growth is in befriending the double-edged intensity of your path. Twice the inspiration, twice the doubt. The practice: when inspiration arrives, capture it immediately — one sentence, one sketch, one note. When doubt arrives, let it pass like weather. Your growth is not in resolving the oscillation but in learning to create productively within it.' },
  { id: 'millman:12:growth', system: 'millman', key: '12', domain: 'growth', traitIds: ['millman:creative-independence', 'millman:cooperative-sensitivity'], text: 'Your growth is in integrating your creative independence with your cooperative nature — not choosing between them but learning when each one leads. The practice: in your current work, identify one moment this week where you led and one where you supported. Notice which felt more natural and which felt more developmental. Your path matures when both feel like you.' },
];
