import type { CanonFragment } from './types';

/** Canon fragments — domain: energy. */
export const ENERGY_FRAGMENTS: CanonFragment[] = [
  // ═══ JUNG — 16 types × energy ═══
  { id: 'jung:INTJ:energy', system: 'jung', key: 'INTJ', domain: 'energy', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Your energy is highest in focused solitude with a complex problem. It drains in meetings, small talk, open-plan offices, and any environment where you must monitor social expectations instead of thinking. The pattern is simple: input restores, output depletes, and social performance is the most expensive output. The practice: audit your calendar weekly and mark each block as restorative or depleting. If the ratio tips past two-to-one depleting, the architecture of your week needs redesign before your energy does.' },
  { id: 'jung:INTP:energy', system: 'jung', key: 'INTP', domain: 'energy', traitIds: ['jung:introversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Your energy follows curiosity. When a problem fascinates you, the energy is inexhaustible. When it bores you, no amount of discipline will compensate. This is not laziness — it is a wiring constraint. The practice: structure your days so the interesting work comes first. Do not spend the morning on administration and expect creative energy in the afternoon. Your best hours are finite; give them to the work that your mind actually wants to do.' },
  { id: 'jung:ENTJ:energy', system: 'jung', key: 'ENTJ', domain: 'energy', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:judging'], text: 'Your energy is abundant and directional. When you have a clear objective, you can sustain effort that exhausts everyone around you. Without an objective, the energy turns restless and destructive — you start optimising things that do not need optimising. The practice: always have a project. The gap between one objective and the next is where your energy becomes anxious. Fill it deliberately, even with something small, and the restlessness stays productive.' },
  { id: 'jung:ENTP:energy', system: 'jung', key: 'ENTP', domain: 'energy', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:thinking', 'jung:perceiving'], text: 'Your energy is stimulation-dependent. Conversations, debates, new environments, and unstructured exploration charge you. Repetition, administration, and silence deplete you. The pattern: you run on intellectual fuel, and when the supply is cut, the engine stalls. The practice: build intellectual stimulation into your routine the way others build exercise. A podcast, a debate with a friend, a new article — daily input prevents the stagnation that you experience as depression.' },
  { id: 'jung:INFJ:energy', system: 'jung', key: 'INFJ', domain: 'energy', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Your energy is deep but narrow. You can sustain profound engagement with one person or one meaningful task for hours. Broad social engagement — parties, networking, group activities — depletes you at a rate that extroverts literally cannot imagine. The practice: after any social event, schedule twice the recovery time you think you need. Your post-social fatigue is not weakness; it is the cost of the deep processing you cannot turn off. Plan for it instead of being surprised by it.' },
  { id: 'jung:INFP:energy', system: 'jung', key: 'INFP', domain: 'energy', traitIds: ['jung:introversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Your energy is mood-sensitive. When you feel aligned — doing meaningful work in a supportive environment — the energy flows. When you feel misaligned, even simple tasks feel impossible. This is not laziness; it is the cost of integrity. The practice: identify the three conditions that most reliably produce your energy (solitude, music, nature, a particular time of day) and protect them. Your energy is not willpower-dependent; it is environment-dependent. Design the environment.' },
  { id: 'jung:ENFJ:energy', system: 'jung', key: 'ENFJ', domain: 'energy', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:judging'], text: 'Your energy comes from people and drains from people in roughly equal measure. A meaningful conversation charges you; an hour of emotional labour depletes you. The practice: distinguish between conversations that give you energy and those that cost you energy. Begin tracking this week. Increase the former and set boundaries on the latter. Your generosity is real, but it requires a budget, and the budget is your energy.' },
  { id: 'jung:ENFP:energy', system: 'jung', key: 'ENFP', domain: 'energy', traitIds: ['jung:extraversion', 'jung:intuition', 'jung:feeling', 'jung:perceiving'], text: 'Your energy is spontaneous and unpredictable. Some days you can do everything; other days the simplest task feels like pushing through mud. The pattern: your energy follows emotional weather, not discipline. The practice: on high-energy days, do the hard things. On low-energy days, do the easy ones. Stop trying to force consistency and start designing for variability. A schedule that accommodates your rhythm will outperform one that fights it.' },
  { id: 'jung:ISTJ:energy', system: 'jung', key: 'ISTJ', domain: 'energy', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Your energy is steady and reliable. You do not experience dramatic peaks or crashes — you produce at a consistent level that accumulates over time. The risk: you do not notice depletion until it becomes breakdown. The practice: schedule rest before you need it. Once per week, take an afternoon completely off — no tasks, no obligations, no productivity. Your steady engine needs maintenance it will never request on its own.' },
  { id: 'jung:ISFJ:energy', system: 'jung', key: 'ISFJ', domain: 'energy', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Your energy is quietly depleted by the emotional labour you perform for everyone around you. You track moods, anticipate needs, and absorb tensions — all without anyone asking. The practice: identify one act of emotional maintenance you do automatically and stop doing it for one week. Not to punish anyone — to discover how much energy it was costing. Your energy returns the moment you stop carrying loads that were never assigned to you.' },
  { id: 'jung:ESTJ:energy', system: 'jung', key: 'ESTJ', domain: 'energy', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:judging'], text: 'Your energy is task-fuelled. Checking things off a list generates momentum that feeds itself. The risk: you optimise for completion and never pause to recover. Burnout arrives not as a crash but as a gradual hardening — less patience, less flexibility, less joy. The practice: build one unstructured hour into each day. No list, no agenda, no goal. This is not laziness; it is the recovery your task-oriented system will never schedule by itself.' },
  { id: 'jung:ESFJ:energy', system: 'jung', key: 'ESFJ', domain: 'energy', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:judging'], text: 'Your energy comes from social connection and drains from social conflict. Harmony charges you; discord costs more than any physical exertion. The practice: after a conflict or a tense interaction, give yourself a recovery window. Call it what it is: "I need thirty minutes to reset." Your social energy is your superpower, and it requires maintenance that looks different from other people\'s rest.' },
  { id: 'jung:ISTP:energy', system: 'jung', key: 'ISTP', domain: 'energy', traitIds: ['jung:introversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Your energy peaks during hands-on, autonomous activity and crashes during prolonged social engagement or repetitive desk work. The body needs to be involved in what the mind is doing. The practice: break sedentary work into ninety-minute blocks and insert something physical — a walk, a repair, a stretch. Your energy model is kinesthetic, and it stalls when the body is idle while the mind is working.' },
  { id: 'jung:ISFP:energy', system: 'jung', key: 'ISFP', domain: 'energy', traitIds: ['jung:introversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Your energy is sensory. Nature, music, art, texture, and physical comfort restore you in ways that conversation and social activity do not. When depleted, your instinct is to retreat into sensory comfort — and this instinct is correct. The practice: do not apologise for needing beauty. A quiet hour with something beautiful is not indulgence; it is the maintenance your system requires. Schedule it with the same seriousness you would schedule exercise.' },
  { id: 'jung:ESTP:energy', system: 'jung', key: 'ESTP', domain: 'energy', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:thinking', 'jung:perceiving'], text: 'Your energy comes from action and variety. Sitting still for extended periods is not rest for you — it is a different kind of depletion. You restore through movement, challenge, and physical engagement. The practice: structure your recovery around activity, not stillness. A game, a run, a competitive hobby — these are your rest, even if they look like exertion to others. Your energy system is the opposite of the default advice; honour its design.' },
  { id: 'jung:ESFP:energy', system: 'jung', key: 'ESFP', domain: 'energy', traitIds: ['jung:extraversion', 'jung:sensing', 'jung:feeling', 'jung:perceiving'], text: 'Your energy is social and sensory. People, music, food, movement, and the feeling of being alive — these charge you. Isolation, monotony, and emotional heaviness drain you. The practice: build at least one social-sensory experience into each day. A meal with a friend, a dance, a walk through a loud, living neighbourhood. Your energy is not trivial because it comes from pleasure; pleasure is your fuel, and it requires intentional access.' },

  // ═══ ENNEAGRAM — 9 cores × energy ═══
  { id: 'ennea:1:energy', system: 'ennea', key: '1', domain: 'energy', traitIds: ['enneagram:reformer-standards', 'enneagram:reformer-critic'], text: 'Your energy is consumed by the inner critic. Before you have done a single task, the critic has already evaluated your intention, predicted your failure, and written the post-mortem. This internal audit runs constantly and costs more than any external work. The practice: name the critic when it speaks. "There is the critic again" externalises it enough to reduce its energy tax. You will not silence it, but you can turn its volume from a shout to a murmur.' },
  { id: 'ennea:2:energy', system: 'ennea', key: '2', domain: 'energy', traitIds: ['enneagram:helper-attunement', 'enneagram:helper-giving'], text: 'Your energy depletes through giving that you do not consciously choose. You give automatically — sensing a need and moving toward it before deciding whether you have the capacity. The practice: pause before the next act of help and ask "do I have energy for this?" If the answer is no, the help will be resentful, and resentful help is worse than none. Your generosity needs a gatekeeper, and the gatekeeper is honest self-assessment.' },
  { id: 'ennea:3:energy', system: 'ennea', key: '3', domain: 'energy', traitIds: ['enneagram:achiever-drive', 'enneagram:achiever-adapt'], text: 'Your energy is performance-fuelled. You can sustain extraordinary output as long as someone is watching and the results are visible. When neither condition is met, your energy drops sharply. The practice: build one private activity into your week that has no audience and no metric. Cooking, journaling, a solitary walk. Your energy system needs to learn that it can operate without applause, and this is how you teach it.' },
  { id: 'ennea:4:energy', system: 'ennea', key: '4', domain: 'energy', traitIds: ['enneagram:individualist-depth', 'enneagram:individualist-longing'], text: 'Your energy follows your emotional state. When inspiration is present, you can create for hours. When it is absent, even basic tasks feel crushing. This is not a discipline problem — it is an energy architecture problem. The practice: create a ritual that reliably shifts your state. Music, a specific walk, a journal prompt. You will never command your emotions into compliance, but you can learn which keys start the engine most reliably.' },
  { id: 'ennea:5:energy', system: 'ennea', key: '5', domain: 'energy', traitIds: ['enneagram:investigator-detach', 'enneagram:investigator-conserve'], text: 'You conserve energy as if it were a finite resource — which, for you, it functionally is. Social interaction, emotional demands, and unexpected obligations deplete you faster than physical exertion. The practice: schedule energy expenditures like budget items. If Tuesday has a social obligation, Wednesday is free. Your energy management is not antisocial; it is the necessary accounting that lets you show up fully when you do.' },
  { id: 'ennea:6:energy', system: 'ennea', key: '6', domain: 'energy', traitIds: ['enneagram:loyalist-vigilance', 'enneagram:loyalist-loyalty'], text: 'Your energy is consumed by scanning. You monitor the environment for threats, run contingency scenarios, and maintain a low-grade alertness that never fully switches off. This is exhausting and invisible. The practice: build one "safe zone" into each day — a place or activity where you grant yourself permission to stop scanning. A locked room, a trusted person, a meditation. Your nervous system needs the signal that, for these twenty minutes, nothing bad will happen.' },
  { id: 'ennea:7:energy', system: 'ennea', key: '7', domain: 'energy', traitIds: ['enneagram:enthusiast-optimism', 'enneagram:enthusiast-variety'], text: 'Your energy is high, scattered, and stimulation-dependent. You can do five things at once and feel energised by all of them. The crash comes when the stimulation stops and you are alone with stillness. The practice: spend fifteen minutes per day in deliberate silence. Not as punishment — as training. Your energy system has no idle gear, and building one prevents the crashes that arrive when the external stimulation unexpectedly stops.' },
  { id: 'ennea:8:energy', system: 'ennea', key: '8', domain: 'energy', traitIds: ['enneagram:challenger-directness', 'enneagram:challenger-control'], text: 'Your energy is volcanic. When it flows, you move mountains. When it is blocked — by bureaucracy, weakness in others, or powerlessness — it turns to anger, which you experience as more energy but which is actually depletion wearing a mask. The practice: distinguish between productive force and reactive force. Productive force builds; reactive force burns. Before you push harder, ask whether pushing is the correct application of your energy or just the loudest one.' },
  { id: 'ennea:9:energy', system: 'ennea', key: '9', domain: 'energy', traitIds: ['enneagram:peacemaker-harmony', 'enneagram:peacemaker-numbing'], text: 'Your energy is present but diffuse. You have capacity — real, substantial capacity — but it is hard to mobilise because your system defaults to rest. Not laziness: energetic conservation so deep it resembles inertia. The practice: use external activation. A timer, a workout, a call with a friend who energises you — something that kicks the engine from idle to first gear. Once you are moving, you sustain beautifully. The challenge is always the start.' },

  // ═══ HUMAN DESIGN — 5 types × energy ═══
  { id: 'hd:Generator:energy', system: 'hd', key: 'Generator', domain: 'energy', traitIds: ['hd:sacral-energy'], text: 'Your sacral energy is self-renewing when you are doing work that genuinely responds to you. Tired at the end of the day is correct — your design uses energy fully and replenishes it through sleep. Exhausted by noon means you are spending sacral energy on the wrong tasks. The practice: track your energy across the day. Note what produced a "lit up" feeling and what produced a "dragging" one. Over a week, the pattern will tell you exactly what your sacral does and does not want to power.' },
  { id: 'hd:Manifesting Generator:energy', system: 'hd', key: 'Manifesting Generator', domain: 'energy', traitIds: ['hd:multi-passionate'], text: 'Your energy is explosive and non-linear. You can work at extraordinary speed on multiple tracks and feel more energised at the end than the beginning — as long as the tracks are ones your sacral chose. Forced work on unchosen tasks drains you twice as fast as it drains a pure Generator. The practice: say no faster. Every unchosen task you accept burns energy that was meant for the chosen ones. Protect the sacral yeses by enforcing the sacral nos.' },
  { id: 'hd:Projector:energy', system: 'hd', key: 'Projector', domain: 'energy', traitIds: ['hd:seeing-gift'], text: 'You have focused, intermittent energy — not the sustained sacral motor of a Generator. Your best work happens in concentrated bursts followed by genuine rest. Trying to match a Generator\'s pace is the fastest route to burnout. The practice: work in ninety-minute deep sessions with real breaks between them. Sleep more than you think you should. Your energy model is not broken — it is different. When you honour its rhythm, your output per hour surpasses types who work twice as long.' },
  { id: 'hd:Manifestor:energy', system: 'hd', key: 'Manifestor', domain: 'energy', traitIds: ['hd:initiating-force'], text: 'Your energy comes in surges. When the creative impulse hits, you can work with an intensity that startles everyone around you. When the surge passes, you need rest — real, unstructured, unapologetic rest. The practice: do not schedule during your rest phase. Block it on the calendar as firmly as you would block a meeting. Your surges depend on your recovery, and your recovery depends on its being genuinely empty. The cycle is: surge, rest, surge. Eliminate the guilt from the rest.' },
  { id: 'hd:Reflector:energy', system: 'hd', key: 'Reflector', domain: 'energy', traitIds: ['hd:mirror-quality'], text: 'Your energy is environmental. In a vital, healthy group, you feel energised. In a depleted or toxic one, you crash without understanding why. The practice: when your energy drops, check the environment before you check yourself. Change the room, leave the building, call a different person. Your energy is not generated internally — it is sampled from the field around you. Managing your energy means managing your exposure.' },

  // ═══ MILLMAN — finals 1–12 × energy ═══
  { id: 'millman:1:energy', system: 'millman', key: '1', domain: 'energy', traitIds: ['millman:creative-independence'], text: 'Your creative energy is blocked by self-doubt and released by action. The longer you deliberate, the lower your energy drops — deliberation feels like preparation and works like a slow leak. The practice: start before you are ready, at whatever scale readiness allows today. The energy you are waiting for arrives after you begin, not before. On the 1 path, motion is the cure for stagnation.' },
  { id: 'millman:2:energy', system: 'millman', key: '2', domain: 'energy', traitIds: ['millman:cooperative-sensitivity'], text: 'Your energy drains through unreciprocated giving. You absorb other people\'s emotional loads and call it empathy, and the difference matters: empathy has a boundary, absorption does not. The practice: check your energy before and after each interaction this week. If someone consistently leaves you depleted, the boundary needs tending, not the friendship necessarily. Your energy is not infinite, and giving without limits is self-depletion wearing a virtue\'s name.' },
  { id: 'millman:3:energy', system: 'millman', key: '3', domain: 'energy', traitIds: ['millman:expressive-gift'], text: 'Suppressed expression is your primary energy leak. When you hold back what you feel, the unexpressed emotion sits in your body as tension, fatigue, or restlessness. The practice: express one thing per day that you would normally hold. A journal entry, a voice message, a candid conversation. Your energy returns the moment the expression leaves your body.' },
  { id: 'millman:4:energy', system: 'millman', key: '4', domain: 'energy', traitIds: ['millman:builder-persistence'], text: 'Your energy is endurance-oriented. You do not peak and crash — you sustain at a moderate, reliable level that compounds over time. The risk: you push through fatigue because your system does not crash dramatically. The practice: rest before you need to. Your steady engine does not send loud distress signals, so schedule maintenance by the calendar, not by the symptom.' },
  { id: 'millman:5:energy', system: 'millman', key: '5', domain: 'energy', traitIds: ['millman:freedom-discipline'], text: 'Your energy spikes in freedom and crashes under constraint. When you choose your own schedule, you are inexhaustible. When someone else dictates it, the same work feels three times heavier. The practice: negotiate one degree of autonomy in your current situation. Even a small freedom — choosing the order of tasks, the location, the start time — restores disproportionate energy.' },
  { id: 'millman:6:energy', system: 'millman', key: '6', domain: 'energy', traitIds: ['millman:visionary-standards'], text: 'Your energy is consumed by the gap between what is and what could be. Seeing the ideal is a constant calculation, and it runs in the background like software you cannot close. The practice: celebrate one improvement per day, however small. Your energy returns when you notice progress, and it drains when you notice only the remaining distance.' },
  { id: 'millman:7:energy', system: 'millman', key: '7', domain: 'energy', traitIds: ['millman:inner-trust'], text: 'Your energy is restored by solitude and inner reflection. You need time to consult your own knowing without external noise. The practice: build one daily pocket of silence — even ten minutes — where no input arrives. Your inner trust regenerates in quiet, and quiet must be deliberately created in a noisy world.' },
  { id: 'millman:8:energy', system: 'millman', key: '8', domain: 'energy', traitIds: ['millman:abundant-leadership'], text: 'Your energy is abundant and leadership-oriented. You have more raw power than most, and the challenge is direction, not quantity. When your energy lacks a worthy target, it becomes restless and destructive. The practice: always have a project large enough to absorb your capacity. When the current one is complete, the next should already be chosen. Your energy needs a container as much as it needs fuel.' },
  { id: 'millman:9:energy', system: 'millman', key: '9', domain: 'energy', traitIds: ['millman:exemplar-integrity'], text: 'Your energy drains when you act out of alignment with your values and restores when you act within them. Integrity is not just a principle for you — it is an energy management system. The practice: identify one current activity that violates your values and reduce it by one hour this week. The energy that returns will be disproportionate to the time saved.' },
  { id: 'millman:10:energy', system: 'millman', key: '10', domain: 'energy', traitIds: ['millman:creative-independence'], text: 'Your energy cycles between creative bursts and periods of renewal. The zero in your path adds a dimension of completion and restart. The practice: when your energy drops, check whether a creative cycle has ended and a new one has not yet begun. The gap between cycles is not illness — it is the pause before the next beginning. Rest in it.' },
  { id: 'millman:11:energy', system: 'millman', key: '11', domain: 'energy', traitIds: ['millman:creative-independence'], text: 'Your energy oscillates between creative euphoria and paralysing doubt. The swings are wider than other paths because both ones are amplified. The practice: when the doubt drops your energy to zero, take the smallest possible creative action. One sentence, one stroke, one note. The energy of the 11 returns through micro-actions, not through waiting for inspiration to arrive.' },
  { id: 'millman:12:energy', system: 'millman', key: '12', domain: 'energy', traitIds: ['millman:creative-independence', 'millman:cooperative-sensitivity'], text: 'Your energy is highest when creative expression and cooperative partnership are both active. Working alone drains the 2 dimension; working collaboratively without creative input drains the 1. The practice: structure your days to include both solo creation time and collaborative time. The 12 path produces its best energy when neither dimension is starved.' },
];
